# Generated by Django 5.2.13 on 2026-09-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='gallery/videos/'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
    ]
