# Generated by Django 5.0.9 on 2026-09-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_galleryitem_video_galleryitem_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='sending_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
