# Generated by Django 5.0.9 on 2026-09-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_companyinfo_sending_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='smtp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='smtp_password_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='smtp_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
