# Generated by Django 5.0.9 on 2026-09-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_companyinfo_smtp_enabled_companyinfo_smtp_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='company/'),
        ),
    ]
