# Generated by Django 5.0.9 on 2026-09-10 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('trigger', models.CharField(choices=[('manual', 'Manual only'), ('application_submitted', 'Application Submitted'), ('application_received', 'Application Received'), ('document_required', 'Additional Document Required'), ('document_rejected', 'Document Rejected'), ('document_verified', 'Document Verified'), ('application_verified', 'Application Verified'), ('application_approved', 'Application Approved'), ('application_rejected', 'Application Rejected'), ('company_new_application', 'Company: New Application')], db_index=True, default='manual', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to_email', models.EmailField(db_index=True, max_length=254)),
                ('cc', models.CharField(blank=True, max_length=500)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_automatic', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='applications.application')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='customers.customerprofile')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='emails.emailtemplate')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='email_attachments/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='emails.emaillog')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
