# Generated by Django 5.0.9 on 2026-09-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_general_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='sending_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='branch',
            name='smtp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='branch',
            name='smtp_password_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='smtp_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
