# Generated by Django 5.0.9 on 2026-09-10 15:16

import core.i18n
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=2, unique=True)),
                ('name', core.i18n.TranslatedField(default=core.i18n.empty_translation)),
                ('flag_emoji', models.CharField(blank=True, max_length=8)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='VisaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('name', core.i18n.TranslatedField(default=core.i18n.empty_translation)),
                ('description', core.i18n.TranslatedField(blank=True, default=core.i18n.empty_translation)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'visa categories',
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='VisaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('name', core.i18n.TranslatedField(default=core.i18n.empty_translation)),
                ('description', core.i18n.TranslatedField(blank=True, default=core.i18n.empty_translation)),
                ('requirements', core.i18n.TranslatedField(blank=True, default=core.i18n.empty_translation)),
                ('application_instructions', core.i18n.TranslatedField(blank=True, default=core.i18n.empty_translation)),
                ('processing_time', core.i18n.TranslatedField(blank=True, default=core.i18n.empty_translation)),
                ('validity', core.i18n.TranslatedField(blank=True, default=core.i18n.empty_translation)),
                ('entry_type', models.CharField(blank=True, choices=[('single', 'Single Entry'), ('double', 'Double Entry'), ('multiple', 'Multiple Entry')], max_length=20)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fee_currency', models.CharField(default='EUR', max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='visas/')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visa_types', to='visas.visacategory')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visa_types', to='visas.country')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('notes', core.i18n.TranslatedField(blank=True, default=core.i18n.empty_translation)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='documents.documenttype')),
                ('visa_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='visas.visatype')),
            ],
            options={
                'ordering': ('display_order', 'id'),
                'unique_together': {('visa_type', 'document_type')},
            },
        ),
    ]
