# Generated by Django 5.0.9 on 2026-09-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Account / card number to pay into'),
        ),
        migrations.AddField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('registration', 'Registration Fee'), ('visa_fee', 'Visa Processing Fee'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
    ]
