# Generated by Django 5.0.9 on 2026-09-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_kind_and_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_owner_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Card owner name'),
        ),
    ]
